export const SET_TOKEN = "SET_TOKEN";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const UNSET_CURRENT_USER = "UNSET_CURRENT_USER";
export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'
export const USER_ME_REQUEST = 'USER_ME_REQUEST'
export const USER_ME_SUCCESS = 'USER_ME_SUCCESS'
export const USER_ME_FAIL = 'USER_ME_FAIL'

export const USER_LOGOUT = 'USER_LOGOUT'
